_format_version: "3.0"
_transform: true

services:
- name: orders-gateway-service
  host: orders-api-it-upstream
  port: 80
  protocol: http
  routes:
  - name: orders-api-route
    paths:
    - /api/orders
- name: orders-gateway-endpoint-sni-service
  host: orders-api-it-upstream
  port: 80
  protocol: http
  routes:
  - name: orders-api-endpoint-sni-route
    paths:
    - /api/orders-endpoint-sni

upstreams:
- name: orders-api-dev-upstream
  targets:
  - target: orders_api_dev:8080
- name: orders-api-prod-upstream
  targets:
  - target: orders_api_prod:8080
- name: orders-api-qa-upstream
  targets:
  - target: orders_api_qa:8080
- name: orders-api-it-upstream
  targets:
  - target: orders_api_it:8080
- name: orders-api-perf-upstream
  targets:
  - target: orders_api_perf:8080

plugins:
- name: jwt
  service: orders-gateway-service
  config:
    claims_to_verify:
    - exp
- name: jwt
  service: orders-gateway-endpoint-sni-service
  config:
    claims_to_verify:
    - exp
- name: dynamic-routing
  service: orders-gateway-service
  config:
    upstream_header_name: X-Upstream-Env
    client_id_header_name: X-Client-Id
    upstreams:
      dev: orders-api-dev-upstream
      prod: orders-api-prod-upstream
      qa: orders-api-qa-upstream
      it: orders-api-it-upstream
      dev_client: orders-api-dev-upstream
      prod_client: orders-api-prod-upstream
      qa_client: orders-api-qa-upstream
      it_client: orders-api-it-upstream
      perf_client: orders-api-perf-upstream
      access-sni-dev.local: orders-api-dev-upstream
      endpoint-sni-qa.local: orders-api-qa-upstream
    access_policy:
      sni: true
      header_name: X-Client-Env
      query_param_name: env
    endpoint:
      sni: false
      header_name: X-Resource-Env
      query_param_name: resource_env
- name: dynamic-routing
  service: orders-gateway-endpoint-sni-service
  config:
    upstream_header_name: X-Upstream-Env
    client_id_header_name: X-Client-Id
    upstreams:
      dev: orders-api-dev-upstream
      prod: orders-api-prod-upstream
      qa: orders-api-qa-upstream
      it: orders-api-it-upstream
      dev_client: orders-api-dev-upstream
      prod_client: orders-api-prod-upstream
      qa_client: orders-api-qa-upstream
      it_client: orders-api-it-upstream
      perf_client: orders-api-perf-upstream
      access-sni-dev.local: orders-api-dev-upstream
      endpoint-sni-qa.local: orders-api-qa-upstream
    access_policy:
      sni: false
      header_name: X-Client-Env
      query_param_name: env
    endpoint:
      sni: true
      header_name: X-Resource-Env
      query_param_name: resource_env

consumers:
- username: dev-client-app
  custom_id: dev_client
  tags:
  - upstream_env:dev
  jwt_secrets:
  - key: dev-client-key
    secret: dev-client-secret
    algorithm: HS256
- username: prod-client-app
  custom_id: prod_client
  tags:
  - upstream_env:prod
  jwt_secrets:
  - key: prod-client-key
    secret: prod-client-secret
    algorithm: HS256
- username: qa-client-app
  custom_id: qa_client
  tags:
  - upstream_env:qa
  jwt_secrets:
  - key: qa-client-key
    secret: qa-client-secret
    algorithm: HS256
- username: it-client-app
  custom_id: it_client
  tags:
  - upstream_env:it
  jwt_secrets:
  - key: it-client-key
    secret: it-client-secret
    algorithm: HS256
- username: perf-client-app
  custom_id: perf_client
  tags:
  - upstream_env:perf
  jwt_secrets:
  - key: perf-client-key
    secret: perf-client-secret
    algorithm: HS256
- username: neutral-client-app
  custom_id: neutral_client
  tags:
  - upstream_env:it
  jwt_secrets:
  - key: neutral-client-key
    secret: neutral-client-secret
    algorithm: HS256

certificates:
- cert: |
    -----BEGIN CERTIFICATE-----
    MIIDWTCCAkGgAwIBAgIUfvoAan7CEt2jtXdvczB/arOVn2MwDQYJKoZIhvcNAQEL
    BQAwHzEdMBsGA1UEAwwUYWNjZXNzLXNuaS1kZXYubG9jYWwwHhcNMjYwMjI0MjAw
    ODQ2WhcNMzYwMjIyMjAwODQ2WjAfMR0wGwYDVQQDDBRhY2Nlc3Mtc25pLWRldi5s
    b2NhbDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKWQOy/Erd5Impo8
    dAEMn8NQZWLbv2OBe8ExTNEdVFkiZKNjk4Imf180Rutfo5cwGHKqaHPm3UR69/gr
    vui0DVL+2GSx0UhUK+BVQt53CFQ+YKEdY5DRGHLyKqDA1gBbmNPOKHFguPGfVeOE
    IteWi21oQfQPW41jtQMWHCviA2sT+RB3DwFVSvLq+BL1QKQ0vH9zO9qKmgOs+ru0
    vnHk6+BII9DyiNPqWFXILd2Cux5z3NANre0sD4UQJbDJK53xnKDulFmDOqLvZTs0
    sSzxia6CTa6QB4R3tyaQdlBgobpOtyFmLgf3xLLqZ4/XEe8MQUykhgRLTLNbA9tE
    SxfZBOkCAwEAAaOBjDCBiTAdBgNVHQ4EFgQUmSDMD6L9WSW0sCqJSjl6MfblnPEw
    HwYDVR0jBBgwFoAUmSDMD6L9WSW0sCqJSjl6MfblnPEwDwYDVR0TAQH/BAUwAwEB
    /zA2BgNVHREELzAtghRhY2Nlc3Mtc25pLWRldi5sb2NhbIIVZW5kcG9pbnQtc25p
    LXFhLmxvY2FsMA0GCSqGSIb3DQEBCwUAA4IBAQA47ss2ufBdQU/vcRmNJjtyrHOe
    zPNg+ZMJm4J+lTda/LtfOBdMui8UJaOWgJ+VUHbJHbBlmJcPJI0cenNB9ufbXrlU
    srvlW03Hex3ZzLTuvnHsEN/sR8wQJQKFvmvepQKf8S5c4Jg7gJgvvqMzhKZbJhKm
    zWzXHuAs0h2h+3GjW9ftbMWjeYFnOjQ6YaW6ClZnyF2lHmQdSLp9yQIhRIdKInnH
    +/Fgdx2d4tFOZeZONTwRcLzpOYUdYQFTnyESe35MLQYjNiFjzVd8JLRl/fNU3q8+
    zf5YsewejGg7w7H1jYG6+MNcpYvr17kf5YP8vIndRc6VVKoMrwRcg5Uk4EpX
    -----END CERTIFICATE-----
  key: |
    -----BEGIN PRIVATE KEY-----
    MIIEuwIBADANBgkqhkiG9w0BAQEFAASCBKUwggShAgEAAoIBAQClkDsvxK3eSJqa
    PHQBDJ/DUGVi279jgXvBMUzRHVRZImSjY5OCJn9fNEbrX6OXMBhyqmhz5t1Eevf4
    K77otA1S/thksdFIVCvgVULedwhUPmChHWOQ0Rhy8iqgwNYAW5jTzihxYLjxn1Xj
    hCLXlottaEH0D1uNY7UDFhwr4gNrE/kQdw8BVUry6vgS9UCkNLx/czvaipoDrPq7
    tL5x5OvgSCPQ8ojT6lhVyC3dgrsec9zQDa3tLA+FECWwySud8Zyg7pRZgzqi72U7
    NLEs8Ymugk2ukAeEd7cmkHZQYKG6TrchZi4H98Sy6meP1xHvDEFMpIYES0yzWwPb
    REsX2QTpAgMBAAECgf8SoWI++z2mwXG/7pY3aOBdl4k47EFxDZr6QmeSDy+axtRu
    5N64yuaZ7IctnR1I6l+6O2M3yjXYepKwP6qoCh5B03DNNvpwuZlVf++hMvX8HRMz
    AEREZc18PX0JUu75P6hzxVS7ndLREZinVx/PZjAbp2r74WEgw52YSEnXJk/uUicD
    ynmNw3H4JBThmNfFtHIRkW1X1S4PR7jlvRv+wJFRcN6tvQ7cNDqF+cOr9X3hs81t
    zUuTS6xZFMbaFe7Mjo+LGk+rKnFNm61tZXB54kZvrGo1b1uSpCLOCxhLIhUWmGQf
    MgDkysh9J0DDdxiYrNzc8QYvRfSu2x2iNWCHcpECgYEA1HsvTzYx3Z3ivyFh2PEy
    dFDuoTMqPwtNbPm7O0WXAYHZ7HrSddFOJTQn7eg5rdqVl+ekY5q2NgTCQruhk1C+
    RL6GYj6DqEjFlYk8tt7BSwaJzR3w1qmGIYB2jMGL6/4i7iyryjZWGDy3vlogyM4W
    ahXeqCPDyUpfdAijiWPZtZECgYEAx3kNemGYGlqKk9WJ99Ob+zxqw0Cz4gkmcAx6
    AfNhn2iXmQRnC3+TZRRXprxj6RBOekMFhBgwz4yDqKYY90QD7GJpAfhBvkfRxzbS
    pNNRG6hWS0Vt39DWFxq0oyomuRyOFMi6W1eED5640BOt3bOzKgFcj2N0lQBRJGA2
    rtbZzdkCgYEAzjr10yMdySTqJGqJJuAMAXtf8ZPQiDo3HvNQd5n2k97tniojxXiu
    KUvzCWVhPk2u7i5FjutluQ5rYgvtKievVNe7ZPWaIaboJ1h5VmDkKSaibzSFQkRt
    zGx8I+fjH92dF6DB6FVOwN2F1bpyoZPti2/ImVeFOwT1mpCb8ci5URECgYAahot3
    ScEbSA0DibL2JMqqRyd/XXxOQ5876TzUQ5QoyZTXQVGeotFr8J+TSZwToxp8gasb
    HMho4Suk4qmRQBcxeQizvVqovg40aqLqTjuL7P/EtK/ewnulyORaikFp/lUaiHLX
    sLScCyRSbzuAruPVYyb23mfjZI5lwvGioGmISQKBgFyoTpibvHZ4s1Ryjd+ueK/O
    0CsqIPZfpNMxd3LVzF5pN2VgnDVNaq8Oomu8/sCHseHbTa+J8V2HOyrHwqr5BB6K
    FqUL7/8vtqZB+xQczK8/+UmDFEBtabcZqofywnm1MfFoiH3qRbbiKSZaUrBTthic
    D4s3D5X+FU0zbdsUqhIJ
    -----END PRIVATE KEY-----
  snis:
  - name: access-sni-dev.local
  - name: endpoint-sni-qa.local
